const data = [
    [
        { "word": "Lion", "category": "Animals", "id": 1 },
        { "word": "Elephant", "category": "Animals", "id": 2 },
        { "word": "Shark", "category": "Animals", "id": 3 },
        { "word": "Giraffe", "category": "Animals", "id": 4 },
        { "word": "Beethoven", "category": "Composers", "id": 5 },
        { "word": "Mozart", "category": "Composers", "id": 6 },
        { "word": "Chopin", "category": "Composers", "id": 7 },
        { "word": "Bach", "category": "Composers", "id": 8 },
        { "word": "Apple", "category": "Fruits", "id": 9 },
        { "word": "Banana", "category": "Fruits", "id": 10 },
        { "word": "Orange", "category": "Fruits", "id": 11 },
        { "word": "Mango", "category": "Fruits", "id": 12 },
        { "word": "Paris", "category": "Cities", "id": 13 },
        { "word": "Rome", "category": "Cities", "id": 14 },
        { "word": "London", "category": "Cities", "id": 15 },
        { "word": "Tokyo", "category": "Cities", "id": 16 }
    ],
    [
        { "word": "Jupiter", "category": "Planets", "id": 17 },
        { "word": "Saturn", "category": "Planets", "id": 18 },
        { "word": "Mars", "category": "Planets", "id": 19 },
        { "word": "Earth", "category": "Planets", "id": 20 },
        { "word": "Vincent", "category": "Artists", "id": 21 },
        { "word": "Picasso", "category": "Artists", "id": 22 },
        { "word": "Dali", "category": "Artists", "id": 23 },
        { "word": "Monet", "category": "Artists", "id": 24 },
        { "word": "Cucumber", "category": "Vegetables", "id": 25 },
        { "word": "Carrot", "category": "Vegetables", "id": 26 },
        { "word": "Lettuce", "category": "Vegetables", "id": 27 },
        { "word": "Potato", "category": "Vegetables", "id": 28 },
        { "word": "Shakespeare", "category": "Writers", "id": 29 },
        { "word": "Hemingway", "category": "Writers", "id": 30 },
        { "word": "Fitzgerald", "category": "Writers", "id": 31 },
        { "word": "Austen", "category": "Writers", "id": 32 }
    ],
    [
        { "word": "Cheese", "category": "Dairy", "id": 33 },
        { "word": "Milk", "category": "Dairy", "id": 34 },
        { "word": "Yogurt", "category": "Dairy", "id": 35 },
        { "word": "Butter", "category": "Dairy", "id": 36 },
        { "word": "Tennis", "category": "Sports", "id": 37 },
        { "word": "Football", "category": "Sports", "id": 38 },
        { "word": "Basketball", "category": "Sports", "id": 39 },
        { "word": "Cricket", "category": "Sports", "id": 40 },
        { "word": "Mozzarella", "category": "Cheese Types", "id": 41 },
        { "word": "Cheddar", "category": "Cheese Types", "id": 42 },
        { "word": "Brie", "category": "Cheese Types", "id": 43 },
        { "word": "Gouda", "category": "Cheese Types", "id": 44 },
        { "word": "Python", "category": "Programming Languages", "id": 45 },
        { "word": "JavaScript", "category": "Programming Languages", "id": 46 },
        { "word": "Ruby", "category": "Programming Languages", "id": 47 },
        { "word": "Java", "category": "Programming Languages", "id": 48 }
    ],
    [
        { "word": "Apple", "category": "Tech Companies", "id": 49 },
        { "word": "Google", "category": "Tech Companies", "id": 50 },
        { "word": "Microsoft", "category": "Tech Companies", "id": 51 },
        { "word": "Amazon", "category": "Tech Companies", "id": 52 },
        { "word": "Beijing", "category": "Chinese Cities", "id": 53 },
        { "word": "Shanghai", "category": "Chinese Cities", "id": 54 },
        { "word": "Hong Kong", "category": "Chinese Cities", "id": 55 },
        { "word": "Chengdu", "category": "Chinese Cities", "id": 56 },
        { "word": "Tea", "category": "Beverages", "id": 57 },
        { "word": "Coffee", "category": "Beverages", "id": 58 },
        { "word": "Juice", "category": "Beverages", "id": 59 },
        { "word": "Water", "category": "Beverages", "id": 60 },
        { "word": "Oxygen", "category": "Elements", "id": 61 },
        { "word": "Hydrogen", "category": "Elements", "id": 62 },
        { "word": "Carbon", "category": "Elements", "id": 63 },
        { "word": "Nitrogen", "category": "Elements", "id": 64 }
    ],
    [
        { "word": "Gold", "category": "Precious Metals", "id": 65 },
        { "word": "Silver", "category": "Precious Metals", "id": 66 },
        { "word": "Platinum", "category": "Precious Metals", "id": 67 },
        { "word": "Diamond", "category": "Precious Metals", "id": 68 },
        { "word": "Eagle", "category": "Birds", "id": 69 },
        { "word": "Penguin", "category": "Birds", "id": 70 },
        { "word": "Owl", "category": "Birds", "id": 71 },
        { "word": "Sparrow", "category": "Birds", "id": 72 },
        { "word": "Romania", "category": "European Countries", "id": 73 },
        { "word": "France", "category": "European Countries", "id": 74 },
        { "word": "Germany", "category": "European Countries", "id": 75 },
        { "word": "Italy", "category": "European Countries", "id": 76 },
        { "word": "Kilimanjaro", "category": "Mountains", "id": 77 },
        { "word": "Everest", "category": "Mountains", "id": 78 },
        { "word": "Alps", "category": "Mountains", "id": 79 },
        { "word": "Andes", "category": "Mountains", "id": 80 }
    ]
]

export { data }